### ISSUE TITLE
Plan for the status links

### ISSUE THREAD

**Issue by rschroll** [SecondLiners/GO3#28]
As mentioned at the end of #25, we need figure out how the links in the gig emails to set status will work.  I really like how the existing system works.  Being able to set a status without needing to log in makes the system usable for people who are unable or uncomfortable using the web interface.  I think the first thing we need to decide is, should existing links keep working after we switch over to the new system.  I see three possibilities:

**Yes, forever.**  In this case, we'll need to match up primary keys in the old and new databases, and we might as well just keep the existing URL structure.

**Yes, but only for future gigs in the old database.** This would allow a seamless transition, but requires potentially two separate systems to handle links.  I'm not opposed to that, though, since it makes it easier to figure out which part we can remove once all these gigs have moved into the past.

**No.** In practice, I imagine that most people will click that link in the email in the first day after receiving the email or not at all.  It may be worth annoying people with broken links for that day or two of the transition to not have to worry about ensuring continuity.

If we go with either of the latter two, I like the idea of hooking it to the plan, instead of the user and gig.  We already have the plan when sending the email, and that's what we'd need to record their response.  This might also obviate the need to encrypt the keys.  I assume that was done so that someone couldn't come up with gig and member keys from separate sources and change someone else's response.  If we identify everything by the plan key, that attack is mitigated.  It would require the plan key to not be guessable, though, and in my testing, it looks like Django + SQLite just increments the primary key for each new row.  If we can get the database to give us pseudo-random primary keys, we can just use that.  Otherwise, I think we do need encryption.

**Comment by aaronoppenheimer** [comment]
I don't think we need to keep the old links working. I agree that people either use them the day they get them or not at all, and we can survive a little bumpiness moving from go2 to go3. Agreed that we should key off the plan instead of the user+gig (I should have done that in the first place).

Here's a project to generate random keys for models that looks pretty good: https://github.com/jbrendel/django-randomprimary

**Comment by rschroll** [comment]
There's also a UUIDField: https://docs.djangoproject.com/en/3.0/ref/models/fields/#uuidfield.  It's a bit ugly, but maybe it's good enough for these links.  Are there other places where the plan key is needed to be displayed?

**Comment by aaronoppenheimer** [comment]
No, the ID is never actually displayed anywhere. If we use a UUID field, we'd still want to jump through the same hoops to ensure it's actually unique (though it always will be in practice), right? That's all the 'django-randomprimary' library does.

**Comment by rschroll** [comment]
UUIDs are designed to be unique (at least until around the year 3400), so I think we could probably not worry about it.

I also found a slightly simpler method here: https://stackoverflow.com/a/37605582.  It takes the time in milliseconds and appends 23 random bits.  The benefit of these approaches is that you don't have to test for collisions. But I suspect if we bump up the minimum size of the randomprimary key, we'd never have collisions in practice either.

**Comment by aaronoppenheimer** [comment]
I'm sure that's true. Any of these is fine with me - I don't see an advantage to having both a unique primary key and a second unique field, but if we're concerned about mixing chocolate and peanut-butter, keeping them separate is OK by me.

**Comment by rschroll** [comment]
Sorry -- the idea would be to use one of these fields as the primary key, in place of the default autoincrementing key.  It appears you can do that just by setting `primary_key=True` on the UUIDField.

**Comment by aaronoppenheimer** [comment]
Oh! So then what's the difference between using something like the library that builds a random id, and having to do the same thing for a UUID field and just calling that the primary key?

**Comment by rschroll** [comment]
Honestly, not a whole lot.  The main difference would be the usage -- do you inherit from another class, or just set a particular attribute in the model.  The benefit of the UUIDField would be that it'll be maintained by Django.  But the django-randomprimary is so simple that we could maintain it should something break it in the future.

I'd be happy with either approach.  If you'd like to let me know which you prefer, I can start implementing it.

**Comment by aaronoppenheimer** [comment]
Use the uuid version, mainly so I can see how you do it!

**Comment by rschroll** [comment]
I'll give it a go.  But everything I know about it is based on 5 minutes of Googling, so don't trust me too much!

**Comment by aaronoppenheimer** [comment]
Ohmygod the future of ~50 lightly-organized brass bands is in your hands!!!!

**Comment by aaronoppenheimer** [comment]
By the way - the Member and Band objects could also use a UUID field, to be used to fetch the calendar streams. But for those objects the ID is visible at times (in the URL for the member and band detail pages) so it needs to be a separate field.
