### ISSUE TITLE
Set timezone properly when sending emails

### ISSUE THREAD

**Issue by rschroll** [SecondLiners/GO3#36]
Right now, all times are reported in the server's timezone, which is probably less than ideal.  It looks like the model has a timezone per band, and none for users, which suggests we should use the band timezone.  Is that right? Or should we let users override the band timezone with their own?

**Comment by aaronoppenheimer** [comment]
Yes, the assumption is that dates and times are in the band's timezone. In fact, go2 ignores timezones altogether and just assumes "2:00" means "local to the band." TZ is only used when generating the calendar stream.

But now that gigs use actual timezone-aware datetimes, we should definitely interpret them in the band's TZ. It's a fair assumption that members exist in the same TZ as the band. We could let the member override it but has never come up as an issue.

I do intend that the TZ could be overridden by the gig - if a Boston band travels to Seattle, the gig should probably record its times in Seattle time. So maybe when we show the gig, if the TZ is overridden, we should specify it in the gig detail page. And the email, I guess.
