### ISSUE TITLE
Things that are currently broken

### ISSUE THREAD

**Issue by rschroll** [SecondLiners/GO3#59]
Just a place for me to keep a list of things that need to be implemented
- [x] images_instructions on member edit page
- [x] Calendar help (linked from preferences)
- [x] ??? Reminder Sent message with member plans
- [x] Mechanism for making members inactive (instead of deleting accounts outright)
- [x] band list in 'add a band' in profile doesn't scroll when list of bands is long.
- [x] Public band profile link (odd redirect?)
- [x] Public view of band details page
- [x] AppStats (GAE stats; probably just remove link?)
- [x] band Calendar URLs
- [x] Band admin panel when user has no name
- [x] Remove 'no section' from gig detail when everyone is in a section
- [x] Grid view
- [x] inviting an existing member should just add them to the band
- [x] Print plans on gig info page
- [x] Send reminder on gig info page
- [x] Gig 'feedback' menu
- [x] Member / Band / MOTD / CryptoKey Admin pages (are the needed w/ Django admin?)
- [x] Delete button on band edit page
- [x] Delete button on member edit page
- [x] Set up sections on band info page
- [x] Gig archive
- [x] Archive button on gig edit
- [x] Calendar view
- [x] "Show brief" on schedule view
- [x] Comment view on gig info page
- [x] Comment submit on gig info page
- [x] Print member plans on gig info page
- [x] Two print buttons when first loading member plans
- [x] Move to trash button on gig edit
- [x] Duplicate button on gig info page
- [x] Gig trashcan
- [x] member Calendar URLs

**Comment by aaronoppenheimer** [comment]
OK if I convert each of these to issues so we can claim them? (I'm working on gig comments)

**Comment by rschroll** [comment]
If you have the energy to do it, go ahead. Alternatively, we can just check
these off when work starts, and then track progress in the PR.
