### ISSUE TITLE
Specify Python version

### ISSUE THREAD

**Issue by rschroll** [SecondLiners/GO3#9]
To avoid issues in development, we ought to choose a minor version of Python to focus on.  At the very least, a minimum version will let us know which features we can use.  But a specific version will help ensure that the versions in `requirements.txt` will work.  (I couldn't get `mysql-connector-python` 1.1.6 installed on my system, which may be due to using Python 3.7.)

**Comment by aaronoppenheimer** [comment]
I'm fine with using 3.7 - I'm on 3.8 for no real reason. 3.7.6 is latest stable 3.7 - good with that?

**Comment by rschroll** [comment]
3.7 is fine with me, but I'm also happy to move to 3.8.  No reason not to join the future.

**Comment by aaronoppenheimer** [comment]
Well, then, future it is. Now we get the walrus operator. Just what I've been waiting for.
